#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
read -p "Are you sure you want to push to \"$BRANCH\" ? (y/n): " -n 1 -r < /dev/tty
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

echo "Push aborted."
exit 1

